### ISSUE TITLE
Should the app rehydrate?

### ISSUE THREAD

**Issue by fetimo** [chemoish/react-universal-tutorial#10]
When I refresh the example app loses its state, does a package like https://github.com/rt2zz/redux-persist need to be added for this functionality?

**Comment by chemoish** [comment]
@fetimo sorry for the late reply, i accidentally clicked on issues, from your other issue, guess i never got the message.

I mean it would make sense that the app loses its state if that state isn't stored anywhere. As it has been quite some time since I have looked at this in any real context, I might be off.

If you wanted to keep the state, you could just store it _somewhere_, and pass that into the store upon initial creation.

In the application I am working on I manage populating the state after querying our backend API's from the express layer (middle tier server). You could store the state separately or even in `localStorage`—depending on your needs.

I haven't looked at that library, but it looks like it's storage mechanism, can be, `localStorage`, which is only available on the client side.

**Comment by fetimo** [comment]
@chemoish likewise I forgot I still had the other issue open until today! 

That makes sense, at the time I was trying to figure out how all of these pieces fit together. State hydration seemed like a fairly big thing that was missing from many examples, or just used `localStorage` as you mention. Using a middle tier server to persist the state makes sense.

Thanks for getting back to me and thanks again for a great starter project 👍
